# Thalloo Starter Template
#
# This project uses Jekyll to integrate with GitHub Pages.
# Configure the basic settings below to configure your copy.

# Your site settings
title: Holocene Arctic Biodiversity Map
description: > # this means to ignore newlines until "baseurl:"
  Visualisations and data exploration for the systematic map 'What evidence exists for temporal variability in Arctic terrestrial and freshwater biodiversity throughout the Holocene?'
baseurl: "/holocene-arctic-biodiversity-map" # the subpath of your site, e.g. /blog
url: "http://acm.im" # the base hostname & protocol for your site
ownername: "CHARTER - a Horizon 2020 consortium"
ownerurl: "http://charter-arctic.org"

# Internal configuration
plugins:
  - jekyll-remote-theme
remote_theme: AndrewIOM/thalloo
markdown: kramdown
collections:
  maps:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"