name: deploy thalloo maps

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: visualisation/processing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK '7.0.x'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run
        run: dotnet run --no-restore --verbosity normal
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: thalloo-static-site
          branch: gh-pages
          