name: deploy thalloo maps

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: src/visualisations/thalloo/processing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK '9.0.x'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Install paket
        run: dotnet tool restore
      - name: Install paket dependencies
        run: dotnet paket install
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run
        run: dotnet run --no-restore --verbosity normal
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src/visualisations/thalloo/thalloo-static-site
          branch: gh-pages
          